

def get_cglu_classes():
    return ['Amoxicillin_0.5MIC', 'Amoxicillin_10MIC', 'Amoxicillin_1MIC', 'Amoxicillin_5MIC', 'Ampicillin_0.5MIC', 'Ampicillin_10MIC', 'Ampicillin_1MIC', 'Ampicillin_5MIC', 'BDM_0.5MIC', 'BDM_10MIC', 'BDM_1MIC', 'BDM_5MIC', 'Carbenicillin_0.5MIC', 'Carbenicillin_10MIC', 'Carbenicillin_1MIC', 'Carbenicillin_5MIC', 'Cefotaxim_0.5MIC', 'Cefotaxim_10MIC', 'Cefotaxim_1MIC', 'Cefotaxim_5MIC', 'Ciprofloxacin_0.5MIC', 'Ciprofloxacin_10MIC', 'Ciprofloxacin_1MIC', 'Ciprofloxacin_5MIC', 'Clarithromycin_0.5MIC', 'Clarithromycin_10MIC', 'Clarithromycin_1MIC', 'Clarithromycin_5MIC', 'Clofazimine_0.5MIC', 'Clofazimine_10MIC', 'Clofazimine_1MIC', 'Clofazimine_5MIC', 'DMSO', 'Doxycycline_0.5MIC', 'Doxycycline_10MIC', 'Doxycycline_1MIC', 'Doxycycline_5MIC', 'Ethambutol_0.5MIC', 'Ethambutol_10MIC', 'Ethambutol_1MIC', 'Ethambutol_5MIC', 'Gepotidacin_0.5MIC', 'Gepotidacin_10MIC', 'Gepotidacin_1MIC', 'Gepotidacin_5MIC', 'Linezolid_0.5MIC', 'Linezolid_10MIC', 'Linezolid_1MIC', 'Linezolid_5MIC', 'Moxifloxacin_0.5MIC', 'Moxifloxacin_10MIC', 'Moxifloxacin_1MIC', 'Moxifloxacin_5MIC', 'Novobiocin_0.5MIC', 'Novobiocin_10MIC', 'Novobiocin_1MIC', 'Novobiocin_5MIC', 'Rifabutin_0.5MIC', 'Rifabutin_10MIC', 'Rifabutin_1MIC', 'Rifabutin_5MIC', 'Rifampicin_0.5MIC', 'Rifampicin_10MIC', 'Rifampicin_1MIC', 'Rifampicin_5MIC', 'Sulfamethoxazole_0.5MIC', 'Sulfamethoxazole_10MIC', 'Sulfamethoxazole_1MIC', 'Sulfamethoxazole_5MIC', 'Trimethoprim_0.5MIC', 'Trimethoprim_10MIC', 'Trimethoprim_1MIC', 'Trimethoprim_5MIC', 'Water']

def get_class_merge_dict():
    class_merge_dict = {'Water_1': 'Water',
                        'Water_2': 'Water',
                        'Water_3': 'Water',
                        'Water_4': 'Water',
                        'Water_5': 'Water',
                        'Water_6': 'Water',
                        'DMSO_1': 'DMSO',
                        'DMSO_2': 'DMSO',
                        'DMSO_3': 'DMSO',
                        'DMSO_4': 'DMSO',
                        'DMSO_5': 'DMSO',
                        'DMSO_6': 'DMSO'}
    return class_merge_dict

def get_cglu_moa_dict():
    cglu_moa_dict = {'Amoxicillin_0.5MIC': 'Cell wall (PBP)',
                    'Amoxicillin_1MIC': 'Cell wall (PBP)',
                    'Amoxicillin_5MIC': 'Cell wall (PBP)',
                    'Amoxicillin_10MIC': 'Cell wall (PBP)',
                    'Ampicillin_0.5MIC': 'Cell wall (PBP)',
                    'Ampicillin_1MIC': 'Cell wall (PBP)',
                    'Ampicillin_5MIC': 'Cell wall (PBP)',
                    'Ampicillin_10MIC': 'Cell wall (PBP)',
                    'BDM_0.5MIC': 'Gyrase',
                    'BDM_1MIC': 'Gyrase',
                    'BDM_5MIC': 'Gyrase',
                    'BDM_10MIC': 'Gyrase',
                    'Carbenicillin_0.5MIC': 'Cell wall (PBP)',
                    'Carbenicillin_1MIC': 'Cell wall (PBP)',
                    'Carbenicillin_5MIC': 'Cell wall (PBP)',
                    'Carbenicillin_10MIC': 'Cell wall (PBP)',
                    'Cefotaxim_0.5MIC': 'Cell wall (PBP)',
                    'Cefotaxim_1MIC': 'Cell wall (PBP)',
                    'Cefotaxim_5MIC': 'Cell wall (PBP)',
                    'Cefotaxim_10MIC': 'Cell wall (PBP)',
                    'Ciprofloxacin_0.5MIC': 'Gyrase',
                    'Ciprofloxacin_1MIC': 'Gyrase',
                    'Ciprofloxacin_5MIC': 'Gyrase',
                    'Ciprofloxacin_10MIC': 'Gyrase',
                    'Clarithromycin_0.5MIC': 'Ribosome',
                    'Clarithromycin_1MIC': 'Ribosome',
                    'Clarithromycin_5MIC': 'Ribosome',
                    'Clarithromycin_10MIC': 'Ribosome',
                    'Clofazimine_0.5MIC': 'Protein synthesis',
                    'Clofazimine_1MIC': 'Protein synthesis',
                    'Clofazimine_5MIC': 'Protein synthesis',
                    'Clofazimine_10MIC': 'Protein synthesis',
                    'DMSO_1': 'Control',
                    'DMSO_2': 'Control',
                    'DMSO_3': 'Control',
                    'DMSO_4': 'Control',
                    'DMSO_5': 'Control',
                    'DMSO_6': 'Control',
                    'Doxycycline_0.5MIC': 'Ribosome',
                    'Doxycycline_1MIC': 'Ribosome',
                    'Doxycycline_5MIC': 'Ribosome',
                    'Doxycycline_10MIC': 'Ribosome',
                    'Ethambutol_0.5MIC': 'Cell wall (Arabinose)',
                    'Ethambutol_1MIC': 'Cell wall (Arabinose)',
                    'Ethambutol_5MIC': 'Cell wall (Arabinose)',
                    'Ethambutol_10MIC': 'Cell wall (Arabinose)',
                    'Gepotidacin_0.5MIC': 'Gyrase',
                    'Gepotidacin_1MIC': 'Gyrase',
                    'Gepotidacin_5MIC': 'Gyrase',
                    'Gepotidacin_10MIC': 'Gyrase',
                    'Linezolid_0.5MIC': 'Ribosome',
                    'Linezolid_1MIC': 'Ribosome',
                    'Linezolid_5MIC': 'Ribosome',
                    'Linezolid_10MIC': 'Ribosome',
                    'Moxifloxacin_0.5MIC': 'Gyrase',
                    'Moxifloxacin_1MIC': 'Gyrase',
                    'Moxifloxacin_5MIC': 'Gyrase',
                    'Moxifloxacin_10MIC': 'Gyrase',
                    'Novobiocin_0.5MIC': 'Gyrase',
                    'Novobiocin_1MIC': 'Gyrase',
                    'Novobiocin_5MIC': 'Gyrase',
                    'Novobiocin_10MIC': 'Gyrase',
                    'Rifabutin_0.5MIC': 'RNA polymerase',
                    'Rifabutin_1MIC': 'RNA polymerase',
                    'Rifabutin_5MIC': 'RNA polymerase',
                    'Rifabutin_10MIC': 'RNA polymerase',
                    'Rifampicin_0.5MIC': 'RNA polymerase',
                    'Rifampicin_1MIC': 'RNA polymerase',
                    'Rifampicin_5MIC': 'RNA polymerase',
                    'Rifampicin_10MIC': 'RNA polymerase',
                    'Sulfamethoxazole_0.5MIC': 'DNA synthesis',
                    'Sulfamethoxazole_1MIC': 'DNA synthesis',
                    'Sulfamethoxazole_5MIC': 'DNA synthesis',
                    'Sulfamethoxazole_10MIC': 'DNA synthesis',
                    'Trimethoprim_0.5MIC': 'DNA synthesis',
                    'Trimethoprim_1MIC': 'DNA synthesis',
                    'Trimethoprim_5MIC': 'DNA synthesis',
                    'Trimethoprim_10MIC': 'DNA synthesis',
                    'Water_1': 'Control',
                    'Water_2': 'Control',
                    'Water_3': 'Control',
                    'Water_4': 'Control',
                    'Water_5': 'Control',
                    'Water_6': 'Control'}

    return cglu_moa_dict
